### ISSUE TITLE
Fixed Navbar

### ISSUE THREAD

**Issue by Sukriti-sood** [vigneshshettyin/Portfolio-v1#4]
Nav Bar position should be fixed for Good User Experience.

**Comment by vigneshshettyin** [comment]
Yup, I'll assign this issue to you. @Sukriti-sood

**Comment by vigneshshettyin** [comment]
Hey, @Sukriti-sood you can also contribute to Open Souce React (https://github.com/vigneshshettyin/Open-Source-React) any kind of react applications are accepted. Do contribute if you are interested. 

Thanks 😃 

Happy Coding!

**Comment by Sukriti-sood** [comment]
Ya ,Sure Will do,  May I know Motive of this Repo.

**Comment by vigneshshettyin** [comment]
> Ya ,Sure Will do, May I know Motive of this Repo.

Just to promote open source.

**Comment by vigneshshettyin** [comment]
> > Ya ,Sure Will do, May I know Motive of this Repo.
> 
> Just to promote open source.

Getting things done before Hacktoberfest 2021 starts.

**Comment by Sukriti-sood** [comment]
> > > Ya ,Sure Will do, May I know Motive of this Repo.
> > 
> > 
> > Just to promote open source.
> 
> Getting things done before Hacktoberfest 2021 starts.

Ook Nyc Initiative.

**Comment by vigneshshettyin** [comment]
> > > > Ya ,Sure Will do, May I know Motive of this Repo.
> > > 
> > > 
> > > Just to promote open source.
> > 
> > 
> > Getting things done before Hacktoberfest 2021 starts.
> 
> Ook Nyc Initiative.

Thanks!

**Comment by vigneshshettyin** [comment]
Hey, @Sukriti-sood do you want to work on this ??

**Comment by Sukriti-sood** [comment]
> Hey, @Sukriti-sood do you want to work on this ??

 I am working on this.

**Comment by vigneshshettyin** [comment]
> > Hey, @Sukriti-sood do you want to work on this ??
> 
> I am working on this.

Okay @Sukriti-sood
